"""Fresh single-video evidence cannot prune a channel or invent authorship."""
from copy import deepcopy
import json
from pathlib import Path
import sys
from tempfile import TemporaryDirectory
import unittest
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'scripts'))
from alden_collection import CollectionStore,identity
from alden_collect import youtube_video_snapshot,threads_post_snapshot,collect_target,capture_source

class VideoSnapshotTests(unittest.TestCase):
    def setUp(self):
        temp=TemporaryDirectory();self.addCleanup(temp.cleanup);self.root=Path(temp.name).resolve();self.store=CollectionStore(self.root)
        self.path=self.root/'video.json';self.target=self.store.register(platform='youtube',original_id='F93TnnxCNvY',kind='video',label='sample',projects=['one'],config={'adapter':'youtube-video','path':str(self.path)})
        self.data={'schema':1,'videos':[{'metadata':{'videoId':'F93TnnxCNvY','url':'https://www.youtube.com/watch?v=F93TnnxCNvY','title':'관측된 제목','description':'관측된 설명','channelName':'표시 이름','publishDate':'2026-10-05'},'tracks':[{'languageCode':'ko','isAutoGenerated':True}],'captions':{'language':'ko','availability':'available','text':'[00:00 - 00:03] 관측된 자막'}}]}
    def write(self):self.path.write_text(json.dumps(self.data,ensure_ascii=False))
    def test_actual_caption_kind_and_unknown_stable_author(self):
        records,relations=youtube_video_snapshot(self.store.target(self.target),self.data,{})
        self.assertTrue(records[0]['caption_is_auto_generated']);self.assertNotIn('author_id',records[0]);self.assertEqual(relations,[])
        self.data['videos'][0]['tracks'].append({'languageCode':'ko','isAutoGenerated':False})
        record=youtube_video_snapshot(self.store.target(self.target),self.data,{})[0][0]
        self.assertIsNone(record['caption_is_auto_generated']);self.assertIn('종류 미확인',record['text'])
    def test_channel_membership_survives_fresh_video_version_and_capture(self):
        channel=self.store.register(platform='youtube',original_id='channel',kind='channel',label='original',projects=['one'])
        self.store.ingest(channel,[{'platform':'youtube','original_id':'F93TnnxCNvY','label':'old','text':'old evidence'},{'platform':'youtube','original_id':'unrelated','label':'keep','text':'keep evidence'}])
        before=self.store.target(channel)['cursor'];self.write();result=collect_target(self.store,self.target);proof=capture_source(self.store,self.target)
        self.assertEqual(result['records'],1);self.assertEqual(proof['state'],'complete');self.assertEqual(self.store.target(channel)['cursor'],before)
        with self.store.database() as db:
            self.assertEqual(db.execute("SELECT COUNT(*) FROM memberships WHERE target_id=? AND availability='available'",(channel,)).fetchone()[0],2)
        graph=self.store.graph_page(projects=['one'],target_id=channel)
        self.assertIn(identity('youtube','unrelated'),{n['id'] for n in graph['nodes']})
    def test_wrong_url_or_video_identity_preserves_prior_checkpoint(self):
        self.write();collect_target(self.store,self.target);before=self.store.target(self.target)['cursor']
        for key,value in [('videoId','wrong-id'),('url','https://www.youtube.com/watch?v=k22cVbRHxcs')]:
            original=deepcopy(self.data);self.data['videos'][0]['metadata'][key]=value;self.write()
            with self.assertRaises(ValueError):collect_target(self.store,self.target)
            self.assertEqual(self.store.target(self.target)['cursor'],before);self.data=original
    def test_failed_caption_access_is_not_empty_or_invented_transcript(self):
        self.data['videos'][0]['captions']={'availability':'access_failed','language':'ko','error':'permission denied'}
        record=youtube_video_snapshot(self.store.target(self.target),self.data,{})[0][0]
        self.assertEqual(record['text'],'관측된 설명');self.assertEqual(record['caption_availability'],'access_failed')
        self.data['videos'][0]['captions']={'availability':'available','language':'ko','text':''}
        with self.assertRaisesRegex(ValueError,'content_unconfirmed'):youtube_video_snapshot(self.store.target(self.target),self.data,{})
    def test_channel_target_and_untimestamped_text_are_not_accepted(self):
        target=self.store.target(self.target);target['kind']='channel'
        with self.assertRaisesRegex(ValueError,'scope_required'):youtube_video_snapshot(target,self.data,{})
        self.data['videos'][0]['captions']['text']='plain text without evidence time'
        with self.assertRaisesRegex(ValueError,'timestamp_unconfirmed'):youtube_video_snapshot(self.store.target(self.target),self.data,{})

    def test_threads_shortcode_identity_and_unknown_account_are_preserved(self):
        target={'platform':'threads','kind':'post','original_id':'DeKQ2ljD3ZO'}
        data={'schema':1,'posts':[{'id':'DeKQ2ljD3ZO','author_handle':'choi.openai','url':'https://www.threads.com/@choi.openai/post/DeKQ2ljD3ZO','text':'관측된 본문','availability':'available','coverage':'main post only; replies and media not read'}]}
        record=threads_post_snapshot(target,data,{})[0][0]
        self.assertNotIn('author_id',record);self.assertEqual(record['author_handle'],'choi.openai')
        for change in [{'availability':'access_failed'},{'author_handle':'different'},{'url':'https://www.threads.com/@choi.openai/post/other'}]:
            altered=deepcopy(data);altered['posts'][0].update(change)
            with self.assertRaises((ValueError,RuntimeError)):threads_post_snapshot(target,altered,{})

    def test_threads_live_post_capture_is_separate_from_account_membership(self):
        path=self.root/'post.json';data={'schema':1,'posts':[{'id':'DeKQ2ljD3ZO','author_handle':'choi.openai','url':'https://www.threads.com/@choi.openai/post/DeKQ2ljD3ZO','text':'관측된 본문','availability':'available','coverage':'main post only'}]};path.write_text(json.dumps(data))
        target=self.store.register(platform='threads',original_id='DeKQ2ljD3ZO',kind='post',label='post',projects=['one'],config={'adapter':'threads-post','path':str(path)})
        collect_target(self.store,target);self.assertEqual(capture_source(self.store,target)['state'],'complete')
        self.assertEqual(self.store.target(target)['kind'],'post')

if __name__=='__main__':unittest.main()
