"""Native host handoff into one declared sample; no network or live models."""
from pathlib import Path
from tempfile import TemporaryDirectory
from datetime import datetime, timedelta, timezone
import hashlib
import json
import os
import sys
import unittest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'scripts'))
from alden_abort import AbortController, AldenCancelled
from alden_collection import CollectionStore, safe_directory
from alden_collect import receive_input, collect_target, json_snapshot


class AcquisitionInputTests(unittest.TestCase):
    def setUp(self):
        tmp = TemporaryDirectory(); self.addCleanup(tmp.cleanup)
        self.root = Path(tmp.name).resolve()
        self.store = CollectionStore(self.root)
        self.controller = AbortController(self.root)
        self.token = self.controller.token()
        self.time = datetime.now(timezone.utc) - timedelta(minutes=5)
        folder = safe_directory(self.root / 'knowledge/acquisition-inputs/video')
        self.current = folder / 'current.json'
        self.write(self.current, self.payload(0))
        self.target = self.store.register(platform='youtube', original_id='F93TnnxCNvY', kind='video', label='sample', projects=['one'], config={'adapter': 'youtube-video', 'path': str(self.current)})
        self.incoming = self.root / 'source.json'
        self.write(self.incoming, self.payload(1))
        self.before = self.store.target(self.target)
        self.old_bytes = self.current.read_bytes()
        self.old_sha = hashlib.sha256(self.old_bytes).hexdigest()

    def payload(self, revision):
        stamp = (self.time + timedelta(minutes=revision)).isoformat()
        return {'schema': 1, 'host': 'Aside', 'observedAt': stamp, 'captionObservedAt': stamp,
                'videos': [{'metadata': {'videoId': 'F93TnnxCNvY', 'url': 'https://www.youtube.com/watch?v=F93TnnxCNvY', 'title': 'sample', 'description': 'revision ' + str(revision)},
                            'tracks': [{'languageCode': 'ko', 'isAutoGenerated': True}],
                            'captions': {'availability': 'available', 'language': 'ko', 'text': '[00:00 - 00:02] 자막'}}]}

    def write(self, path, payload):
        path.write_text(json.dumps(payload)); path.chmod(0o600)

    def receive(self, expected=None):
        return receive_input(self.store, self.target, self.incoming, expected or self.old_sha, token=self.token)

    def test_received_bytes_backup_replay_and_target_state_are_separate_from_collect(self):
        result = self.receive()
        self.assertEqual(result['state'], 'received')
        self.assertFalse(result['collected'])
        backup = Path(result['backup'])
        self.assertEqual(backup.read_bytes(), self.old_bytes)
        self.assertEqual(backup.stat().st_mode & 0o777, 0o600)
        self.assertEqual(self.current.read_bytes(), self.incoming.read_bytes())
        self.assertEqual(self.store.target(self.target), self.before)
        self.assertEqual(self.receive()['state'], 'unchanged')
        self.assertEqual(len(list(backup.parent.glob('*.json'))), 1)
        report = collect_target(self.store, self.target)
        self.assertEqual(report['records'], 1)
        self.assertEqual(self.store.graph_page(projects=['one'])['nodes'][0]['label'], 'sample')

    def test_changed_current_blocks_overwrite_and_preserves_the_other_writer(self):
        self.write(self.current, self.payload(2))
        raw = self.current.read_bytes()
        with self.assertRaisesRegex(RuntimeError, 'current_changed'): self.receive()
        self.assertEqual(self.current.read_bytes(), raw)

    def test_stale_observation_and_wrong_video_do_not_publish(self):
        for change in ('stale', 'identity', 'missing_time', 'old_caption'):
            value = self.payload(1)
            if change == 'stale': value = self.payload(-1)
            elif change == 'identity': value['videos'][0]['metadata']['videoId'] = 'k22cVbRHxcs'
            elif change == 'missing_time': value.pop('observedAt')
            else: value['captionObservedAt'] = self.payload(-1)['captionObservedAt']
            self.write(self.incoming, value)
            with self.subTest(change=change), self.assertRaises(ValueError): self.receive()
            self.assertEqual(self.current.read_bytes(), self.old_bytes)

    def test_failed_caption_does_not_remove_last_confirmed_content(self):
        value = self.payload(1); value['videos'][0]['captions'] = {'availability': 'access_failed'}
        self.write(self.incoming, value)
        with self.assertRaisesRegex(ValueError, 'caption_unconfirmed'): self.receive()
        self.assertEqual(self.current.read_bytes(), self.old_bytes)

    def test_denied_or_disabled_target_cannot_receive(self):
        for field in ('enabled', 'permission'):
            with self.store.database() as db:
                if field == 'enabled': db.execute('UPDATE targets SET enabled=0 WHERE id=?', (self.target,))
                else: db.execute("UPDATE target_projects SET permission='denied' WHERE target_id=?", (self.target,))
            with self.subTest(field=field), self.assertRaisesRegex(ValueError, 'scope_denied'): self.receive()
            self.assertEqual(self.current.read_bytes(), self.old_bytes)
            with self.store.database() as db: db.execute('UPDATE targets SET enabled=1 WHERE id=?', (self.target,))

    def test_cancelled_handoff_leaves_source_and_checkpoint_untouched(self):
        self.controller.abort('fixture')
        with self.assertRaises(AldenCancelled): self.receive()
        self.assertEqual(self.current.read_bytes(), self.old_bytes)
        self.assertEqual(self.store.target(self.target), self.before)

    def test_symlink_fifo_and_outside_destination_fail_closed(self):
        self.incoming.unlink(); self.incoming.symlink_to(self.current)
        with self.assertRaisesRegex(ValueError, 'symlink'): self.receive()
        self.incoming.unlink(); os.mkfifo(self.incoming, 0o600)
        with self.assertRaisesRegex(ValueError, 'budget'): json_snapshot(self.incoming)
        with self.store.database() as db:
            db.execute('UPDATE targets SET config=? WHERE id=?', (json.dumps({'adapter': 'youtube-video', 'path': str(self.root / 'current.json')}), self.target))
        with self.assertRaisesRegex(ValueError, 'outside_scope'): self.receive()

    def test_threads_post_is_bound_to_one_shortcode_and_observed_time(self):
        folder = safe_directory(self.root / 'knowledge/acquisition-inputs/post')
        current = folder / 'current.json'
        def post(revision):
            return {'schema': 1, 'host': 'local', 'observed_at': (self.time + timedelta(minutes=revision)).isoformat(),
                    'posts': [{'id': 'DeKQ2ljD3ZO', 'url': 'https://www.threads.com/@choi.openai/post/DeKQ2ljD3ZO',
                               'author_handle': 'choi.openai', 'text': 'source ' + str(revision),
                               'availability': 'available', 'coverage': 'main post only'}]}
        self.write(current, post(0)); self.write(self.incoming, post(1))
        tid = self.store.register(platform='threads', original_id='DeKQ2ljD3ZO', kind='post', label='post', projects=['two'], config={'adapter': 'threads-post', 'path': str(current)})
        sha = hashlib.sha256(current.read_bytes()).hexdigest()
        result = receive_input(self.store, tid, self.incoming, sha, token=self.token)
        self.assertEqual(result['state'], 'received')
        value = post(2); value['posts'][0]['availability'] = 'access_failed'; self.write(self.incoming, value)
        raw = current.read_bytes()
        with self.assertRaisesRegex(RuntimeError, 'access_not_confirmed'):
            receive_input(self.store, tid, self.incoming, hashlib.sha256(raw).hexdigest(), token=self.token)
        self.assertEqual(current.read_bytes(), raw)


if __name__ == '__main__': unittest.main()
